---
ID: "27e72952-4340-4ba5-b049-a6621d7210e1"
Parent: "eeb2c022-a947-4007-81eb-9d32b1dd1d87"
Template: "eeb2c022-a947-4007-81eb-9d32b1dd1d87"
Path: /sitecore/templates/CoveoModule/Search/List Value Parameter/__Standard Values
DB: master
SharedFields:
- ID: "860d9bfe-ddca-49d2-a7a4-59a7ef6f2d32"
  Hint: Value
  Value: $name
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140221T150835
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
