---
ID: "ac102896-c0b0-4a10-937b-e1b75b1c92ae"
Parent: "a58691e3-af59-485e-b821-304b1c4a9499"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/CoveoModule/Search/Facet Parameters/Navigation/FacetNumberOfValuesInFacetSearch
DB: master
SharedFields:
- ID: "56776edf-261c-4abc-9fe7-70c618795239"
  Hint: __Help link
  Value: |
    <link url="https://coveo.github.io/search-ui/components/facet.html#options.numberofvaluesinfacetsearch" linktype="external" />
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Integer
- ID: "b118496a-0f78-4a27-b55f-0a6c4b0b0fe1"
  Hint: Default value
  Value: 15
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1443
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Number of values to display in the facet search results
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: Specifies the number of values displayed in the facet search results popup. The default value is 15.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140210T143419
