---
ID: "9d1243a0-2dc4-4afd-b322-7b1ebc0bd4e0"
Parent: "ceae335b-2de6-4fd4-9532-901981c81ff3"
Template: "ceae335b-2de6-4fd4-9532-901981c81ff3"
Path: /sitecore/templates/CoveoModule/Search/Top Results/Top Result/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150410T151029
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "70489be8-1f7b-4879-90e7-46f0d9d9e0ce"
      Hint: TopResultQueries
      Value: $name
