---
ID: "c067f61b-8305-447c-938d-1dae110e4195"
Parent: "ceae335b-2de6-4fd4-9532-901981c81ff3"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/CoveoModule/Search/Top Results/Top Result/Basic Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150410T150809
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
