---
ID: "68d17135-a94f-452f-a7df-1d311f707a0c"
Parent: "fe13e0a5-b777-4489-8968-2ed7a0cebfee"
Template: "fe13e0a5-b777-4489-8968-2ed7a0cebfee"
Path: /sitecore/templates/CoveoModule/Search/Sorts/Sorts Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {E7725E1D-FC56-416C-B04C-13D5DE61FF6E}
    {2ECCB5A3-910F-4035-B6FF-AC3F6D416BAB}
    {7E77178E-D6D1-4CB0-B8D8-1CD5B62E19FF}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160310T094226
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
