---
ID: "3aa75004-194c-4f17-9892-53cbd3853647"
Parent: "2ab40180-5f88-44e2-9052-e910bda4cc58"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/CoveoModule/Search/Tab Parameters/Basic Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: "-10"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160219T150200
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
