---
ID: "e7ac3991-3269-412c-bab7-6729cfc5076f"
Parent: "8861e1c8-ebc0-42af-ad9b-dcd2cf6f71c6"
Template: "8861e1c8-ebc0-42af-ad9b-dcd2cf6f71c6"
Path: /sitecore/templates/CoveoModule/Search/Facet Range Parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140523T115034
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
