---
ID: "2b229abc-6b0b-44b1-b271-f067ee855721"
Parent: "af0e427b-fe86-410c-82a4-1080d49d1d97"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/CoveoModule/Search/Facet Parameters/Advanced Settings/FacetEnableSettingsFacetState
DB: master
SharedFields:
- ID: "56776edf-261c-4abc-9fe7-70c618795239"
  Hint: __Help link
  Value: |
    <link linktype="external" url="https://developers.coveo.com/display/public/JsSearchV1/Facet+Component#FacetComponent-enableSettingsFacetState" />
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Checkbox
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2743
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Enable Save Facet State option in Settings menu
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: Specifies whether the save state option is available in the facet settings menu.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160219T133109
