---
ID: "4bedcd0c-fb9a-46d0-a5ea-a1287224faac"
Parent: "22e07e51-f379-4dfc-957a-5fee605dd118"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/CoveoModule/Search/Sort Parameters/Basic Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: "-2"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20131011T110600
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
