---
ID: "857638f1-4852-4935-a8ba-d92e62eb4c3e"
Parent: "a9c7e37a-a6f3-4c78-b7b6-7d75f64f58eb"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/CoveoModule/Search/Facet Parameters/Options/FacetEnableSettings
DB: master
SharedFields:
- ID: "39847666-389d-409b-95bd-f2016f11eed5"
  Hint: Unversioned
  Type: Checkbox
  Value: 0
- ID: "56776edf-261c-4abc-9fe7-70c618795239"
  Hint: __Help link
  Value: |
    <link url="https://coveo.github.io/search-ui/components/facet.html#options.enablesettings" linktype="external" />
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Checkbox
- ID: "b118496a-0f78-4a27-b55f-0a6c4b0b0fe1"
  Hint: Default value
  Value: 1
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2543
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Enable settings button
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: Specifies if the settings button is enabled. Default value is true.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140210T143419
